#!/bin/sh
#
# Try to renew a midi file by reading and writing it using mito.
# If the header data, track lengths and the event list reported by mito
# is the same for the original and the new file, replace the original by
# the new file.

tmp=/tmp/.$$
trap "rm -f $tmp.* " 0

test $# = 0 &&
echo "usage: mnew file..." >& 2 && exit 1

for i; do
  if mito -qqq -hle "$i" -o $tmp.new | sed 1d > $tmp.list && [ -f $tmp.new ]
  then
    if cmp -s $tmp.new $i
    then
      echo "$i" unchanged
    else
      if mito -qqq -hle $tmp.new | sed 1d | cmp -s $tmp.list -
      then
        rm -f "$i" && mv -f $tmp.new "$i" && echo "$i" renewed
      else
        echo "$i" BUGGY
      fi
    fi
  else
    echo "$i" corrupted
  fi
done
