########################################################################
# $Id: Makefile,v 1.1 1996/02/05 16:13:42 kilian Exp $
#
# Makefile for `cm/include'.
# As you can see, there is nothing to make in this directory.
#
# $Log: Makefile,v $
# Revision 1.1  1996/02/05 16:13:42  kilian
# checked in with -k by kilian at 1996/04/01 19:10:11
#
# Revision 1.1  1996/02/05  16:13:42  kilian
# Initial revision
#
#
########################################################################
include $(TOP)/Rules
